version: "3.8"

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_GEMINI_API_KEY=${REACT_APP_GEMINI_API_KEY}
    env_file:
      - .env.development
    stdin_open: true
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_GEMINI_API_KEY=${REACT_APP_GEMINI_API_KEY}
    ports:
      - "80:80"
    environment:
      - REACT_APP_GEMINI_API_KEY=${REACT_APP_GEMINI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
